name = "dev-badge"
main = "index.js"
workers_dev = true
compatibility_date = "2022-08-04"
send_metrics = false
minify = true



[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[vars]
 #
[build]
 #