name = "dev-badge"
main = "./dist/worker.js"
workers_dev = true
compatibility_date = "2022-08-04"
send_metrics = false
# main = "./index.js" # /tmp
# account_id = "****"

[placement]
mode = "smart"

# PRODUCTION #
[env.production]
name = "dev-badge"
main = "./dist/worker.js"

[env.production.vars]

[env.production.build]
command = "npm run build"
watch_dir = "./mods"

# DEVELOPEMT #
[env.development]
main = "./dist/development_worker.js" #
# main = "./index.js" #

[env.development.vars]

[env.development.build]
command = "npm run build"
watch_dir = "./mods"


[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[vars]
 #
[build]
 #