name: DeployDryRun
on:
  workflow_dispatch:
  pull_request_target:
    branches: '**'
    types: [opened]
  push:
    branches: [ master ]
    paths:
    - '**.js'


jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
       node-version: 'latest'
    - run: npm install --save

    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
       apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
       command: deploy --dry-run
       preCommands: |
        wrangler --version
        # wrangler secret:bulk ./example.secrets.json
       postCommands: |
        wrangler secret list
        # wrangler deployments list
    env:
     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
